<?xml version = "1.0" encoding="UTF-8"?>
<!DOCTYPE channel [

<!ELEMENT channel (item+,title,link,image*,language?,description)>
<!ATTLIST channel version CDATA "">
<!ELEMENT item (title,link,description?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT image (title, link, url)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT title (#PCDATA)>
]>
<channel version = "1.0">
	<item>
		<title>What is the mass of the Earth on moon</title>
		<link>www.youtube.com/mass</link>
		<description>The answer will blow your mind!</description>
	</item>
	<title>Vsauce</title>
	<link>www.youtube.com/vsauce</link>
	<image>
		<title>me</title>
		<link>www/blabla.com/me.png</link>
		<url>www/blabla.com/me.png</url>
	</image>
	<language>English</language>
	<description>I make science videos</description>
</channel>