<?xml version="1.0"?>
<!DOCTYPE games [
  <!ELEMENT games (game)>
  <!ELEMENT game (home-team, ex-team,goals,yellows,reds)>
  <!ELEMENT home-team (#PCDATA)>
  <!ELEMENT ex-team (#PCDATA)>
  <!ELEMENT goals (goal*)>
  <!ELEMENT yellows (player*)>
  <!ELEMENT reds (player*)>
  <!ATTLIST game score CDATA "">
  <!ELEMENT goal (player)>
  <!ELEMENT player (#PCDATA)>
  <!ATTLIST goal minute CDATA "" 
  type CDATA ""
  >
]>
<games>
    <game score="1-1">
           <home-team>Roma</home-team>
           <ex-team>Lazio</ex-team>
           <goals>
              <goal minute="15">
              <player>Klose</player>
              </goal>
              <goal minute="85" type="penalty">
              <player>Tox</player>
              </goal>
           </goals>
        <yellows>
           <player>Tox</player>
           <player>Hernanes</player>
        </yellows>
        <reds>
           <player>Kjaer</player>
        </reds>
    </game>
</games>